server:
  address: localhost
  port: 8081
  servlet: # https://oingdaddy.tistory.com/407 : Springboot Session Timeout 설정
    session:
      timeout: 30m

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daliyshop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test
  # thymeleaf 설정
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

mybatis:
  configuration:
    multiple-result-sets-enabled: false #여러 개의 결과 집합을 반환하는지 여부 설정 (단일 결과 집합 반환)
    map-underscore-to-camel-case: true # 컬럼 이름에 대하여 _를 camel case로 변환하여 매핑할 것인지 설정 (user_id -> userId로 매핑)
    call-setters-on-nulls: true # null값을 가지는 프로퍼티에 대해 setter를 호출할지 여부 (null값을 가지는 프로퍼티에 대하여 setter 호출)
    jdbc-type-for-null: varchar # null값을 가지는 컬럼의 JDBC 타입 설정 (null값을 가지는 컬럼은 VARCHAR 타입으로 처리)
    default-fetch-size: 500 # 결과 집합을 한번에 가져올 최대 행 수
  type-aliases-package: com.shopping.daliyShop.model
  mapper-locations: classpath:mybatis/mapper/*.xml
